### ISSUE TITLE
install in Packstack mitaka gives error

### ISSUE THREAD

**Issue by szahirim** [yeasy/easyOVS#17]
When it's installation finished, and after entering easyovs command, it gives this error:
[root@localhost ~]# easyovs
Traceback (most recent call last):
  File "/usr/bin/easyovs", line 4, in <module>
    __import__('pkg_resources').run_script('easyovs==0.5', 'easyovs')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 637, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 650, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'python-keystoneclient<=1.6,>=1.0' distribution was not found and is required by easyovs

**Comment by yeasy** [comment]
the error msg is clear, it only supports python-keystoneclient<=1.6,>=1.0, while other versions are not verified.
