### ISSUE TITLE
Running Issue with easyOvs

### ISSUE THREAD

**Issue by gr790** [yeasy/easyOVS#19]
Hello,

I have RHEL 7.4 ( Maipo) release, I just installed this software to diagnose the openstack system. 
It took a while to install it, because it was failing because of some python packages....I had to reran the script again and again ...and it successfully installed.

Now when I try to run it..fails..

```
[root@openstack-controller easyOVS(keystone_admin)]# easyovs
Traceback (most recent call last):
  File "/usr/bin/easyovs", line 4, in <module>
    __import__('pkg_resources').run_script('easyovs==0.5', 'easyovs')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/easyovs-0.5-py2.7.egg/EGG-INFO/scripts/easyovs", line 11, in <module>

  File "build/bdist.linux-x86_64/egg/easyovs/cli.py", line 14, in <module>
  File "build/bdist.linux-x86_64/egg/easyovs/bridge_ctrl.py", line 8, in <module>
  File "build/bdist.linux-x86_64/egg/easyovs/neutron.py", line 7, in <module>
  File "/usr/lib/python2.7/site-packages/python_keystoneclient-1.6.0-py2.7.egg/keystoneclient/v2_0/__init__.py", line 1, in <module>
    from keystoneclient.v2_0.client import Client  # noqa
  File "/usr/lib/python2.7/site-packages/python_keystoneclient-1.6.0-py2.7.egg/keystoneclient/v2_0/client.py", line 20, in <module>
    from keystoneclient import httpclient
  File "/usr/lib/python2.7/site-packages/python_keystoneclient-1.6.0-py2.7.egg/keystoneclient/httpclient.py", line 61, in <module>
    from keystoneclient import session as client_session
  File "/usr/lib/python2.7/site-packages/python_keystoneclient-1.6.0-py2.7.egg/keystoneclient/session.py", line 32, in <module>
    osprofiler_web = importutils.try_import("osprofiler.web")
  File "/usr/lib/python2.7/site-packages/oslo_utils/importutils.py", line 103, in try_import
    return import_module(import_str)
  File "/usr/lib/python2.7/site-packages/oslo_utils/importutils.py", line 73, in import_module
    __import__(import_str)
  File "/usr/lib/python2.7/site-packages/osprofiler/web.py", line 20, in <module>
    from osprofiler import profiler
  File "/usr/lib/python2.7/site-packages/osprofiler/profiler.py", line 26, in <module>
    from osprofiler import notifier
  File "/usr/lib/python2.7/site-packages/osprofiler/notifier.py", line 16, in <module>
    from osprofiler.drivers import base
  File "/usr/lib/python2.7/site-packages/osprofiler/drivers/__init__.py", line 1, in <module>
    from osprofiler.drivers import base  # noqa
  File "/usr/lib/python2.7/site-packages/osprofiler/drivers/base.py", line 18, in <module>
    from oslo_log import log
  File "/usr/lib/python2.7/site-packages/oslo_log/log.py", line 47, in <module>
    from oslo_log import _options
  File "/usr/lib/python2.7/site-packages/oslo_log/_options.py", line 39, in <module>
    help='If set to true, the logging level will be set to '
  File "/usr/lib/python2.7/site-packages/oslo.config-1.15.0-py2.7.egg/oslo_config/cfg.py", line 982, in __init__
    super(BoolOpt, self).__init__(name, type=types.Boolean(), **kwargs)
TypeError: __init__() got an unexpected keyword argument 'mutable'
[root@openstack-controller easyOVS(keystone_admin)]#
[root@openstack-controller easyOVS(keystone_admin)]#

```

please suggest, what could be issue.

Thanks.

**Comment by yeasy** [comment]
The tool has not been tested for recent openstack releases.
I suppose some api has been change due to "    super(BoolOpt, self).__init__(name, type=types.Boolean(), **kwargs)".

**Comment by gr790** [comment]
I noticed it....I installed it on my controller node, and it did some nasty things...I couldn't run neutron command after that...
I will see what could be issue if I have time to debug your tool.....But I need some tool which could identify what could be issue with networking in openstack.....

I am closing it.

Thanks,
Rahul.

**Comment by gr790** [comment]
This tool doesn't support latest Release of Openstack specially rdo...it will overwrite your existing python setup with old one if you have latest RDO installed....

Please be careful.
